### ISSUE TITLE
Block-wise initialization scheme

### ISSUE THREAD

**Issue by denkorzh** [facebookresearch/neuralvolumes#2]
Hi, 
is there any paper describing the used block-wise weight initialization scheme?

https://github.com/facebookresearch/neuralvolumes/blob/8c5fad49b2b05b4b2e79917ee87299e7c1676d59/models/utils.py#L73

**Comment by stephenlombardi** [comment]
Hi,
I remember I heard about it from this github issue: https://github.com/Lasagne/Lasagne/issues/862 which references this tech report: https://arxiv.org/abs/1707.02937

**Comment by denkorzh** [comment]
Thank you!
