### ISSUE TITLE
Any plan to release all data that presented in the paper?

### ISSUE THREAD

**Issue by ziruiw-dev** [facebookresearch/neuralvolumes#6]
Hi @stephenlombardi ,

Thanks for sharing this great work. I was wondering do you have any plan to release all the data that you used in the paper (apart from the dryice)?

Best,
Zirui

**Comment by Jia-Wei-Liu** [comment]
Hi @stephenlombardi ,

Excellent work and thanks for sharing your code. I have the same question and wonder if you have any plan to release all the data that you used in the paper? Thank you very much!

Best regards.

**Comment by stephenlombardi** [comment]
Hi, we currently don't have plans to release all data from the paper. However, we plan to release some additional data in the coming months.
