### ISSUE TITLE
code for hybrid rendering (section 6.2) doesn't exist?

### ISSUE THREAD

**Issue by andrewsonga** [facebookresearch/neuralvolumes#7]
Hello, 

First of all, thank you for releasing the code for your seminal work. I really think neural volumes is one of the works that popularized differentiable rendering and inspired future works such as neural radiance fields. 

My question is whether this codebase includes the code for the hybrid rendering method outlined in section 6.2 of the paper. I'm trying to fit Neural Volumes to multi-view video of a full-body human being, similar to the 5th subfigure in Fig. 1 of the main paper, but after reading it more carefully it seems as though I would need to use hybrid rendering to be able to render the fine details of the human being. 

Could you 
1) confirm the existence of hybrid rendering in this codebase AND 
2) whether or not hybrid rendering was used to render the full-bodied human being in Fig. 1 of the main paper.

Thank you in advance.

**Comment by stephenlombardi** [comment]
Hi,

Unfortunately the code release does not include code for hybrid rendering. However, the 5th subfigure in Fig. 1 does not use hybrid rendering, it's just plain Neural Volumes.

You're right that hybrid rendering can improve resolution where a mesh is used. Fig. 9 in the paper demonstrates examples that we tried hybrid rendering on (we have a mesh for the head and neck, and neural volumes models the rest (e.g., hair and shoulders)). 

If you're interested, we have just released code for a follow-up paper to Neural Volumes called [Mixture of Volumetric Primitives](https://github.com/facebookresearch/mvp) which does take a mesh as input and does something a little more sophisticated than the hybrid rendering from Neural Volumes.

-- Steve

**Comment by maobenz** [comment]
Hello,
Thanks for releasing your code. I am impressed by your work. Now I hope to run your code with my our dataset. I have two questions.

Firstly, I see the pose.txt is used in the code to put the objects in the center. If I use my own data, will the file still work?

Secondly, I see the code set the raypos is among -1 and 1. Is it the matrix in this pose file that narrows the range to -1 to 1? My own dataset' range is different.

Thirdly, does the code limit the scope of the template? Does it have to be between 0-255?

Thanks a lot in advance!
