### ISSUE TITLE
How Can I train and render a Person Image

### ISSUE THREAD

**Issue by LuanDalOrto** [facebookresearch/neuralvolumes#9]
Hi my name is Luan I am trying to render a Person Image but I am not being able to run can you create and for me a folder with the Setting setup to use a person image? Thank you.

**Comment by stephenlombardi** [comment]
Hi Luan, are you trying to train the model on your own dataset? For that you'll need to write a custom class extending the PyTorch Dataset interface (see https://github.com/facebookresearch/neuralvolumes/blob/main/data/dryice1.py for an example of a custom Dataset implementation that you can follow). 

If you're just trying to render some of the pre-trained data, unfortunately this release does not contain training data with humans in it.
